In [1]:
import numpy as np

In [5]:
l = [1,2,3,4]
res = 0
for i in l:
    res += i
print res

10


In [7]:
def fun():
    i = []
    for i in range(100000):
        l.append(i)

%timeit fun()

10 loops, best of 3: 37.5 ms per loop


In [8]:
def fun():
    i = []
    for i in range(1000000):
        l.append(i)

%timeit fun()

1 loop, best of 3: 341 ms per loop


In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a = np.arange(10).reshape(2,5)

In [11]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
a.shape

(2L, 5L)

In [13]:
b = np.arange(16).reshape(2,2,4)

In [14]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
npl = np.array(l)

In [21]:
npl = np.array(l)
def npFun():
    res = 0
    for i in npl:
        res += i
        
print res
%timeit npFun()

10


C:\Users\ZekeLabs\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: overflow encountered in long_scalars


1 loop, best of 3: 2.18 s per loop


In [22]:
def listFun():
    res = 0
    for i in l:
        res += 0
        
%timeit listFun()

1 loop, best of 3: 679 ms per loop


In [23]:
np.array(l)

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [24]:
np.array(2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [25]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
np.ones( (5,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [27]:
np.linspace(1,20,100)

array([  1.        ,   1.19191919,   1.38383838,   1.57575758,
         1.76767677,   1.95959596,   2.15151515,   2.34343434,
         2.53535354,   2.72727273,   2.91919192,   3.11111111,
         3.3030303 ,   3.49494949,   3.68686869,   3.87878788,
         4.07070707,   4.26262626,   4.45454545,   4.64646465,
         4.83838384,   5.03030303,   5.22222222,   5.41414141,
         5.60606061,   5.7979798 ,   5.98989899,   6.18181818,
         6.37373737,   6.56565657,   6.75757576,   6.94949495,
         7.14141414,   7.33333333,   7.52525253,   7.71717172,
         7.90909091,   8.1010101 ,   8.29292929,   8.48484848,
         8.67676768,   8.86868687,   9.06060606,   9.25252525,
         9.44444444,   9.63636364,   9.82828283,  10.02020202,
        10.21212121,  10.4040404 ,  10.5959596 ,  10.78787879,
        10.97979798,  11.17171717,  11.36363636,  11.55555556,
        11.74747475,  11.93939394,  12.13131313,  12.32323232,
        12.51515152,  12.70707071,  12.8989899 ,  13.09

In [28]:
a = np.array([1,2,3,4])
b = np.arange(4)

In [29]:
a + b

array([1, 3, 5, 7])

In [30]:
a + 6

array([ 7,  8,  9, 10])

In [31]:
b ** 2

array([0, 1, 4, 9])

In [33]:
help(np.random.randint)

Help on built-in function randint:

randint(...)
    randint(low, high=None, size=None)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution in the
    "half-open" interval [`low`, `high`). If `high` is None (the default),
    then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    

In [37]:
data = np.random.randint(5,high=10,size=15)

In [38]:
np.sqrt(data)

array([ 2.82842712,  3.        ,  2.82842712,  3.        ,  2.23606798,
        2.44948974,  2.82842712,  3.        ,  3.        ,  2.64575131,
        2.82842712,  2.82842712,  2.82842712,  2.44948974,  2.82842712])

In [39]:
a

array([1, 2, 3, 4])

In [40]:
b

array([0, 1, 2, 3])

In [42]:
np.add(a,b)

array([1, 3, 5, 7])

In [43]:
np.sum(a)

10

In [44]:
np.argmax(a)

3

In [45]:
np.mean(a)

2.5

In [47]:
def f(x,y):
    return  x + y

np.fromfunction(f, (2,4))

array([[ 0.,  1.,  2.,  3.],
       [ 1.,  2.,  3.,  4.]])

In [51]:
l[0:10]

[1, 2, 3, 4, 0, 1, 2, 3, 4, 5]

In [52]:
k = np.arange(100).reshape(10,10)

In [56]:
k[0:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [54]:
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
k[4, 5:7]

array([45, 46])

In [59]:
k.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
k.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [62]:
j = np.arange(64).reshape(4,4,4)

In [63]:
j.reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [64]:
a = np.floor(10*np.random.random((2,2)))

In [65]:
b = np.floor(10*np.random.random((2,2)))

In [66]:
a

array([[ 5.,  5.],
       [ 3.,  0.]])

In [67]:
b

array([[ 1.,  4.],
       [ 3.,  4.]])

In [68]:
np.random.random((2,2))

array([[ 0.96457689,  0.16279269],
       [ 0.89496701,  0.61372704]])

In [70]:
np.vstack((a,b))

array([[ 5.,  5.],
       [ 3.,  0.],
       [ 1.,  4.],
       [ 3.,  4.]])

In [71]:
np.hstack((a,b))

array([[ 5.,  5.,  1.,  4.],
       [ 3.,  0.,  3.,  4.]])

In [72]:
data = np.array([1,2,3,3,4,4,5,52,33,1,1,1,])

In [74]:
data[data > 5]

array([52, 33])

In [75]:
data[data == 1]

array([1, 1, 1, 1])

In [76]:
np.square(data)

array([   1,    4,    9,    9,   16,   16,   25, 2704, 1089,    1,    1,
          1])

In [77]:
np.log(data)

array([ 0.        ,  0.69314718,  1.09861229,  1.09861229,  1.38629436,
        1.38629436,  1.60943791,  3.95124372,  3.49650756,  0.        ,
        0.        ,  0.        ])

In [78]:
data = np.array([1,2,3,2,-1,-23,1,-12])

In [79]:
np.sign(data)

array([ 1,  1,  1,  1, -1, -1,  1, -1])

In [85]:
data = np.array(None)

In [86]:
np.isnan(None)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [88]:
d = np.array([2,3,4,7,6,9,2])

In [90]:
d[np.greater_equal(d,5)]

array([7, 6, 9])

In [91]:
points = np.arange(-5,5,0.01)

In [98]:
points.ndim

1

In [94]:
# meshgrid takes two 1D arrays & produces two 2D matrices corresponding to all pairs in two arrays
xs, xy = np.meshgrid(points,points)

In [100]:
xs.shape

(1000L, 1000L)

In [96]:
xy

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [102]:
xy

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [103]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [105]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [106]:
cond = np.array([True, False, True, True, False])

In [107]:
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]

In [108]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [109]:
np.where(cond,xarr,yarr)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [114]:
rarr = np.random.randint(10, high=20, size=(4,4))

In [115]:
np.where(rarr > 15, 1, 0)

array([[1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0]])

In [116]:
rarr

array([[16, 10, 16, 11],
       [18, 16, 13, 13],
       [14, 14, 13, 13],
       [19, 14, 17, 11]])

In [120]:
rarr.mean(axis=0)

array([ 16.75,  13.5 ,  14.75,  12.  ])

In [121]:
rarr.mean(axis=1)

array([ 13.25,  15.  ,  13.5 ,  15.25])

In [122]:
rarr.sort()

In [123]:
rarr

array([[10, 11, 16, 16],
       [13, 13, 16, 18],
       [13, 13, 14, 14],
       [11, 14, 17, 19]])

In [124]:
names = np.array(['abc','def','abc','jkl','mas','jkl'])

In [125]:
np.unique(names)

array(['abc', 'def', 'jkl', 'mas'], 
      dtype='|S3')

In [131]:
np.save('file2',rarr)

In [133]:
np.load('file2.npy')

array([[10, 11, 16, 16],
       [13, 13, 16, 18],
       [13, 13, 14, 14],
       [11, 14, 17, 19]])

In [137]:
x = np.array([ [1.,2.,3.], [4.,5.,6.]])

In [138]:
y = np.array([ [6.0, 23.0], [-1,7], [8,9]])

In [142]:
z = x.dot(y)

In [147]:
from numpy.linalg import inv, qr

In [143]:
inv(z)

array([[ 0.23205128, -0.08205128],
       [-0.08589744,  0.03589744]])

In [148]:
qr(z)

(array([[-0.385593  , -0.92266897],
        [-0.92266897,  0.385593  ]]), array([[ -72.61542536, -191.68103652],
        [   0.        ,   10.7415194 ]]))

In [152]:
np.random.normal(size=4)

array([-0.83831537, -1.87129582, -1.30766521,  1.96287507])

In [151]:
help(np.random.normal)

Help on built-in function normal:

normal(...)
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float
        Mean ("centre") of the distribution.
    scale : float
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are

In [154]:
data  = np.random.normal(loc=0, scale=0.25, size=(5,5))

NameError: name 'display' is not defined